### ISSUE TITLE
keyboard module not found

### ISSUE THREAD

**Issue by daledozer** [zMenta/StoneShard_save_backup_tool#2]
any chance i can get a hand with what I'm doing wrong

Python 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

= RESTART: D:\xxxxx\StoneShard_save_backup_tool-main\run.py
Traceback (most recent call last):
** IDLE Internal Exception: 
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python310\lib\idlelib\run.py", line 580, in runcode
    exec(code, self.locals)
  File "D:\SteamLibrary\steamapps\common\Stoneshard\StoneShard_save_backup_tool-main\run.py", line 1, in <module>
    import keyboard
ModuleNotFoundError: No module named 'keyboard'

**Comment by zMenta** [comment]
Sorry for the delay. Please send me a message on discord. zMenta#9423
